version: '3'
services:
  nginx:
    image: nginx:1.15
    ports:
      - 90:80
    volumes:
      - ./source:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  php-fpm:
    build: ./php-fpm
    volumes:
      - ./source:/var/www/html
