version: '3'
 
services:
  nginx:
    build: ./docker/nginx
    ports:
      - 10088:80
    volumes:
      - ./src:/var/www
  php-fpm:
    build: ./docker/php-fpm
    volumes:
      - ./src/php:/var/www/html